create table tb_carrinho (id int4 generated by default as identity, id_produto int4, id_carrinho int4, primary key (id));
create table tb_categoria (id int4 generated by default as identity, nome varchar(255), primary key (id));
create table tb_produto (id int4 generated by default as identity, descricao varchar(255), foto varchar(255), disponivel boolean, preco float8, categoria_id int4, primary key (id));
create table tb_usuario (id int4 generated by default as identity, usuario int4, bairro varchar(255), cep varchar(255), cidade varchar(255), complemento varchar(255), cpf varchar(255), email varchar(255), estado varchar(255), fone varchar(255), nome varchar(255), numero varchar(255), perfil varchar(255), rua varchar(255), senha varchar(255), primary key (id));
create table tb_venda (id int4 generated by default as identity, data_compra varchar(255), id_usuario int4, valor_total float8, usuario_id int4, primary key (id));
alter table if exists tb_carrinho add constraint FKldcdirmhw0cdc8i6aqqy5vudb foreign key (id_produto) references tb_produto;
alter table if exists tb_carrinho add constraint FKckwtpytqj0hnpumv2pm8awedw foreign key (id_carrinho) references tb_venda;
alter table if exists tb_produto add constraint FK1ksfe2oumgjxke3oc5op41lej foreign key (categoria_id) references tb_categoria;
alter table if exists tb_venda add constraint FK79hud7c7jsw3n6r1xkcuykjn5 foreign key (usuario_id) references tb_usuario;